  steps:
    - name: maker
      order: 1
      scripts:
        initial:
          script: "apk add --no-cache git make musl-dev go"
        processing:
          script: "go version"
        proceed: 
          script: "echo 'proceed'"
    
    - name: checker
      order: 2
      scripts:
        initial:
          script: echo 'initial'
        processing:
          script: echo 'processing'
        proceed: 
          script: echo 'proceed'